// Mock AI Service for testing when backend is not available
class MockAIService {
  constructor() {
    this.delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  }

  async generateText(prompt, options = {}) {
    // Simulate API delay
    await this.delay(2000);

    return {
      success: true,
      data: {
        content: `🚀 **Generated Content for: "${prompt}"**

This is a mock AI-generated LinkedIn post based on your topic. In a real implementation, this would be generated by OpenAI's GPT-4.

✨ **Key Points:**
• Professional insights on ${prompt}
• Engaging content structure
• Call-to-action included

**Style:** ${options.writingStyle || "Professional"}
**Category:** ${options.postCategory || "Thought Leadership"}
**Length:** ${options.length || "Medium"}

#AI #Innovation #LinkedIn #SocialSonic

---
*This is a demo response. Connect your OpenAI API key for real AI generation.*`,
        metadata: {
          writingStyle: options.writingStyle,
          postCategory: options.postCategory,
          length: options.length,
          model: "mock-gpt-4",
          tokensUsed: 150,
          generationTime: 2000,
          creditsUsed: 1,
        },
      },
    };
  }

  async generateImage(prompt, options = {}) {
    await this.delay(3000);

    return {
      success: true,
      data: {
        imageUrl: `https://via.placeholder.com/512x512/4F46E5/FFFFFF?text=${encodeURIComponent(
          prompt.substring(0, 20)
        )}`,
        revisedPrompt: `Enhanced prompt: ${prompt} in ${options.style} style`,
        originalPrompt: prompt,
        metadata: {
          style: options.style,
          aspectRatio: options.aspectRatio,
          model: "mock-dall-e-3",
          generationTime: 3000,
          creditsUsed: 2,
        },
      },
    };
  }

  async getSuggestions(type, context = "") {
    await this.delay(1000);

    const suggestions = {
      text: [
        "The future of AI in business transformation",
        "5 leadership lessons from successful entrepreneurs",
        "How remote work is reshaping company culture",
        "The importance of continuous learning in tech",
        "Building resilient teams in uncertain times",
      ],
      image: [
        "Professional headshot with modern office background",
        "Team collaboration in a bright workspace",
        "Technology and innovation concept art",
        "Success and growth visualization",
        "Modern business meeting setup",
      ],
    };

    return {
      success: true,
      suggestions: suggestions[type] || suggestions.text,
    };
  }

  async getContentHistory(userId, options = {}) {
    await this.delay(500);

    return {
      success: true,
      data: [
        {
          _id: "mock-1",
          type: "text",
          prompt: "AI in business",
          generatedContent: { content: "Sample generated content..." },
          createdAt: new Date().toISOString(),
          metadata: { style: "Professional" },
        },
        {
          _id: "mock-2",
          type: "image",
          prompt: "Business meeting",
          generatedContent: { imageUrl: "https://via.placeholder.com/300x300" },
          createdAt: new Date().toISOString(),
          metadata: { style: "Realistic" },
        },
      ],
    };
  }

  async getUserStats(userId) {
    await this.delay(300);

    return {
      success: true,
      data: {
        contentStats: [
          { type: "text", count: 5 },
          { type: "image", count: 3 },
        ],
        credits: {
          used: 8,
          limit: 100,
          remaining: 92,
        },
      },
    };
  }

  async healthCheck() {
    return {
      success: true,
      status: "Mock service running",
      timestamp: new Date().toISOString(),
    };
  }
}

export default new MockAIService();
